name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TOKEN: ${{ secrets.TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: |
          newman run "JSONPlaceholder API.postman_collection.json" \
            --environment "Development.postman_environment.json" \
            --env-var "token=$TOKEN"
            --env-var "baseUrl=$BASE_URL"
            --env-var "userId=$USER_ID"
            --reporters cli,htmlextra \
            --reporter-htmlextra-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: report.html